spring:
  datasource:
    url: jdbc:mariadb://kids-care.c7wdhtetojg1.ap-northeast-2.rds.amazonaws.com:3306/kids_care
    username: yeonjae
    password: yeonjae1!
    driver-class-name: org.mariadb.jdbc.Driver

  thymeleaf:
    cache: false

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: zhdhfhd33@gmail.com #구글계정이 필요해서 신민건 것을 사용함.
    password:  #비밀번호임. 노출되면 안됨. 깃헙에 올릴 때는 지움.
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true


logging:
  level:
    org.hibernate.SQL: info #debug
    org.hibernate.type: trace
