spring:
  datasource:
    url: jdbc:mariadb://kids-care.c7wdhtetojg1.ap-northeast-2.rds.amazonaws.com:3306/kids_care
    username: yeonjae
    password: yeonjae1!
    driver-class-name: org.mariadb.jdbc.Driver

  thymeleaf:
    cache: false

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true


logging:
  level:
    org.hibernate.SQL: error #info #debug
    org.hibernate.type: warn
    #org.hibernate.type: trace
